### ISSUE TITLE
Update email for functional form submissions

### ISSUE THREAD

**Issue by daviddarnes** [brandonkim12/brandonkim12.github.io#1]
Hey! Thanks for using my Jekyll theme. I’ve noticed I’m getting form verification submissions from your site, if you update this line to your own email it should fix the issue: https://github.com/brandonkim12/brandonkim12.github.io/blob/0b61ae848d221a9162232535bfa29e395d43102a/_config.yml#L84

Might be worth changing the rest of the details from me to your own details 👍

**Comment by brandonkim12** [comment]
Oh, I just saw your message. Thank you for your advice! :)
